[tool.poetry]
name = "volga"
version = "0.1.0"
description = "Real-time Feature/ML platform"
authors = ["Andrey Novitskiy <valera.dirty@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
