name: volga-maturin-build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd $GITHUB_WORKSPACE/rust && mkdir -p rust_builds
      - uses: PyO3/maturin-action@v1
        with:
          args: -i python3.10 --target-dir $GITHUB_WORKSPACE/rust/rust_builds -m $GITHUB_WORKSPACE/rust/Cargo.toml
      - uses: actions/upload-artifact@v4
        with:
          name: volga-rust-x86_64-py310
          path: $GITHUB_WORKSPACE/rust/rust_builds/
