name: volga
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff --output-format=github .
        continue-on-error: true
      - name: Start local Ray
        run: ray start --head
      # TODO when all tests are fixed replace with pytest
      - name: Run test test_job_graph.py
        run: python volga/streaming/api/job_graph/test_job_graph.py
      - name: Run test test_stream.py
        run: python volga/streaming/api/stream/test_stream.py
      - name: Run test test_stream.py
        run: python volga/streaming/runtime/core/execution_graph/test_execution_graph.py
      - name: Run test test_operators.py
        run: python volga/api/dataset/test_operators.py
      - name: Stop local Ray
        run: ray stop